//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutSync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutSync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string CheckNewVersionCaption {
            get {
                return ResourceManager.GetString("CheckNewVersionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorDialogCaption {
            get {
                return ResourceManager.GetString("ErrorDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.facebook.com/profile.php?id=.
        /// </summary>
        internal static string FacebookProfileUrl {
            get {
                return ResourceManager.GetString("FacebookProfileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 59c78df122290d00e4078a11bae801fc.
        /// </summary>
        internal static string FBAppKey {
            get {
                return ResourceManager.GetString("FBAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 63bbc81f55842bb178353a6b5496d761.
        /// </summary>
        internal static string FBSecret {
            get {
                return ResourceManager.GetString("FBSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched Contacts ({0}).
        /// </summary>
        internal static string MatchedContactsHeader {
            get {
                return ResourceManager.GetString("MatchedContactsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version is available. Do you want to get it?.
        /// </summary>
        internal static string NewVersionAvailableMessage {
            get {
                return ResourceManager.GetString("NewVersionAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contacts have been selected..
        /// </summary>
        internal static string NoContactsToSyncMessage {
            get {
                return ResourceManager.GetString("NoContactsToSyncMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Matches Found.
        /// </summary>
        internal static string NoMatchesCaption {
            get {
                return ResourceManager.GetString("NoMatchesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of your Facebook friends could be matched with Outlook contacts..
        /// </summary>
        internal static string NoMatchesMessage {
            get {
                return ResourceManager.GetString("NoMatchesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates are currently available..
        /// </summary>
        internal static string NoNewVersionAvailableMessage {
            get {
                return ResourceManager.GetString("NoNewVersionAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building friends list.
        /// </summary>
        internal static string Progress_BuildingFriendsList {
            get {
                return ResourceManager.GetString("Progress_BuildingFriendsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating lists.
        /// </summary>
        internal static string Progress_CreatingLists {
            get {
                return ResourceManager.GetString("Progress_CreatingLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching Facebook friends to Outlook contacts.
        /// </summary>
        internal static string Progress_Matching {
            get {
                return ResourceManager.GetString("Progress_Matching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalizing contacts.
        /// </summary>
        internal static string Progress_NormalizingContacts {
            get {
                return ResourceManager.GetString("Progress_NormalizingContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Pictures.
        /// </summary>
        internal static string RemovePicturesCaption {
            get {
                return ResourceManager.GetString("RemovePicturesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done removing pictures..
        /// </summary>
        internal static string RemovePicturesDoneMessage {
            get {
                return ResourceManager.GetString("RemovePicturesDoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **WARNING** This will remove pictures from ALL your Outlook contacts. It is meant for debugging and troubleshooting purposes only. Do you want to continue?.
        /// </summary>
        internal static string RemovePicturesWarning {
            get {
                return ResourceManager.GetString("RemovePicturesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the {0} selected Outlook contacts from Facebook?.
        /// </summary>
        internal static string SyncConfirmationMessage {
            get {
                return ResourceManager.GetString("SyncConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Contacts.
        /// </summary>
        internal static string SyncContactsCaption {
            get {
                return ResourceManager.GetString("SyncContactsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmatched Contacts ({0}).
        /// </summary>
        internal static string UnmatchedContactsHeader {
            get {
                return ResourceManager.GetString("UnmatchedContactsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Outlook contacts were successfully updated..
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access the update server. Check your Internet connection..
        /// </summary>
        internal static string UpdateFailedMessage {
            get {
                return ResourceManager.GetString("UpdateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.melsam.com/outsync/update.aspx?ver={0}.
        /// </summary>
        internal static string UpdateUrl {
            get {
                return ResourceManager.GetString("UpdateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating .
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
    }
}
